services:
  back:
    build:
      context: ./Backend
      args:
        - PORT=4000
      target: prod
    image: moelmasry456/webserver
    depends_on:
      - mongo
      - redis
    command: ["npm", "run", "dev"]
    networks:
      - backend-net
    volumes:
      - ./Backend:/code
      - /code/node_modules
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    networks:
      - backend-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: MO
      MONGO_INITDB_ROOT_PASSWORD: "123456789"
    volumes:
      - mongo-vol:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: MO
      ME_CONFIG_MONGODB_ADMINPASSWORD: "123456789"
      ME_CONFIG_MONGODB_URL: mongodb://MO:123456789@mongo:27017/myData?authSource=admin
      ME_CONFIG_BASICAUTH: false
    networks:
      - backend-net
  redis:
    image: redis:alpine
    networks:
      - backend-net
    ports:
      - "6300:6379"

  nginx:
    image: nginx:stable-alpine
    networks:
      - backend-net
    depends_on:
      - back
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
networks:
  backend-net:
volumes:
  mongo-vol:
